// <auto-generated />
using System;
using LowCodePlatform.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LowCodePlatform.Backend.Data.Migrations.PlatformSqlServer
{
    [DbContext(typeof(PlatformSqlServerDbContext))]
    partial class PlatformSqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LowCodePlatform.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("actor");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details_json");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("installation_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trace_id");

                    b.HasKey("AuditLogId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.EntityDefinition", b =>
                {
                    b.Property<Guid>("EntityDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_definition_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("EntityDefinitionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("entity_definition", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.EntityRecord", b =>
                {
                    b.Property<Guid>("EntityRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_record_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_json");

                    b.Property<Guid>("EntityDefinitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_definition_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("EntityRecordId");

                    b.HasIndex("EntityDefinitionId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("entity_record", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.FieldDefinition", b =>
                {
                    b.Property<Guid>("FieldDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("field_definition_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EntityDefinitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_definition_id");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int")
                        .HasColumnName("max_length");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("FieldDefinitionId");

                    b.HasIndex("EntityDefinitionId");

                    b.HasIndex("EntityDefinitionId", "Name")
                        .IsUnique();

                    b.ToTable("field_definition", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.Installation", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("installation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_version");

                    b.Property<string>("ReleaseChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("release_channel");

                    b.Property<DateTime>("ReleaseDateUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("release_date_utc");

                    b.Property<string>("SupportedVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supported_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UpgradeWindowDays")
                        .HasColumnType("int")
                        .HasColumnName("upgrade_window_days");

                    b.HasKey("InstallationId");

                    b.ToTable("installation", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.Property<Guid>("UpgradeRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("upgrade_run_id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("installation_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_version");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trace_id");

                    b.HasKey("UpgradeRunId");

                    b.HasIndex("InstallationId");

                    b.ToTable("upgrade_run", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRunStep", b =>
                {
                    b.Property<Guid>("UpgradeRunStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("upgrade_run_step_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasColumnName("attempt");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_key");

                    b.Property<Guid>("UpgradeRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("upgrade_run_id");

                    b.HasKey("UpgradeRunStepId");

                    b.HasIndex("UpgradeRunId");

                    b.ToTable("upgrade_run_step", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("WorkflowDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_definition_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition_json");

                    b.Property<string>("InboundTriggerSecretSha256Hex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inbound_trigger_secret_sha256_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleCron")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("schedule_cron");

                    b.Property<bool>("ScheduleEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("schedule_enabled");

                    b.Property<DateTime?>("ScheduleNextDueUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("schedule_next_due_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("WorkflowDefinitionId");

                    b.HasIndex("Name");

                    b.HasIndex("ScheduleEnabled", "ScheduleNextDueUtc");

                    b.ToTable("workflow_definition", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowRun", b =>
                {
                    b.Property<Guid>("WorkflowRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_run_id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at_utc");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("state");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trace_id");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("State");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("workflow_run", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowStepRun", b =>
                {
                    b.Property<Guid>("WorkflowStepRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_step_run_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasColumnName("attempt");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorConfigPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error_config_path");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error_message");

                    b.Property<string>("OutputJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("output_json");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("state");

                    b.Property<string>("StepConfigJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_config_json");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_key");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_type");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("WorkflowStepRunId");

                    b.HasIndex("State");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("workflow_step_run", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.EntityRecord", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.EntityDefinition", "EntityDefinition")
                        .WithMany()
                        .HasForeignKey("EntityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityDefinition");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.FieldDefinition", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.EntityDefinition", "Entity")
                        .WithMany("Fields")
                        .HasForeignKey("EntityDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRunStep", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.UpgradeRun", "UpgradeRun")
                        .WithMany("Steps")
                        .HasForeignKey("UpgradeRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpgradeRun");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowRun", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowStepRun", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.WorkflowRun", "WorkflowRun")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.EntityDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.WorkflowRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
