// <auto-generated />
using System;
using LowCodePlatform.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LowCodePlatform.Backend.Data.Migrations.Platform
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260318165201_InitialPlatform")]
    partial class InitialPlatform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("LowCodePlatform.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("details_json");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("installation_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trace_id");

                    b.HasKey("AuditLogId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.Installation", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("installation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_version");

                    b.Property<string>("ReleaseChannel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("release_channel");

                    b.Property<DateTime>("ReleaseDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date_utc");

                    b.Property<string>("SupportedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("supported_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UpgradeWindowDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upgrade_window_days");

                    b.HasKey("InstallationId");

                    b.ToTable("installation", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.Property<Guid>("UpgradeRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("upgrade_run_id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at_utc");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("installation_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_version");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trace_id");

                    b.HasKey("UpgradeRunId");

                    b.HasIndex("InstallationId");

                    b.ToTable("upgrade_run", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRunStep", b =>
                {
                    b.Property<Guid>("UpgradeRunStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("upgrade_run_step_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at_utc");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("step_key");

                    b.Property<Guid>("UpgradeRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("upgrade_run_id");

                    b.HasKey("UpgradeRunStepId");

                    b.HasIndex("UpgradeRunId");

                    b.ToTable("upgrade_run_step", (string)null);
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRunStep", b =>
                {
                    b.HasOne("LowCodePlatform.Backend.Models.UpgradeRun", "UpgradeRun")
                        .WithMany("Steps")
                        .HasForeignKey("UpgradeRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpgradeRun");
                });

            modelBuilder.Entity("LowCodePlatform.Backend.Models.UpgradeRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
