apiVersion: v1
kind: Service
metadata:
  name: {{ include "lowcode-platform.backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lowcode-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lowcode-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
