apiVersion: v1
kind: Service
metadata:
  name: {{ include "lowcode-platform.frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lowcode-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lowcode-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
